spring:
  application:
    name: redistoolkit
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:postgresql://localhost:5432/javatest
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 50
        id:
          new_generator_mappings: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql: TRACE
        orm.jdbc.bind: TRACE